#version 450 core

layout (local_size_x = 32, local_size_y = 32) in;

layout (binding = 0, rgba32f) uniform image2D sourse;

layout (binding = 1, rgba32f) uniform image2D data;

// 输入1：最低高度
uniform float Low;
// 输入2：最高高度
uniform float High;

void main(){
   float ans = clamp(imageLoad(sourse, ivec2(gl_GlobalInvocationID.xy)).r, Low, High);
   imageStore(data, ivec2(gl_GlobalInvocationID.xy), vec4(ans, ans,ans, ans));
}
