#version 450 core

layout (local_size_x = 32, local_size_y = 32) in;

layout (binding = 0, r32f) uniform image2D sourse;

layout (binding = 1, r32f) uniform image2D data;

// 地形最大高度
uniform float TerrainHeight;

float Invert(float src){
   float ans = TerrainHeight - src;
   return ans;
}

void main(){
   float ans = imageLoad(sourse, ivec2(gl_GlobalInvocationID.xy)).r;
   // TODO
   ans = Invert(ans);
   imageStore(data, ivec2(gl_GlobalInvocationID.xy), vec4(ans, ans,ans, ans));
}
